import argparse
import json
import pathlib

#import matplotlib.pyplot as plt
# Using for interactive graph portability
import numpy as np
import pandas as pd
import plotly.graph_objects as go
import plotly.subplots as subplots

def load_locals(file: pathlib.Path):
    dec = json.JSONDecoder()
    with open(file, "r") as f:
        data = dec.decode(f.read())
    return data

def func_df(func_locals: dict):
    df = pd.DataFrame(func_locals)
    df = df.reset_index().rename(columns={'index': 'step'})
    df = pd.melt(df, id_vars='step', var_name='var_name', value_name='value')
    return df

def plot_func(fname: str, local_df: pd.DataFrame, func_locals: dict, fig, row=None, col=None):
    #fig, ax = plt.subplots()
    steps = [i for i in range(len(list(func_locals.values())[0]))]
    #ax.stackplot(steps, func_locals.values(), labels=func_locals.keys(), alpha=0.8)
    #ax.legend(loc='right', reverse=True)
    #ax.set_title(fname)
    #ax.set_xlabel('Source Line')
    #ax.set_ylabel('Bytes Used')
# ad#d tick at every 200 million people
    ##ax.yaxis.set_minor_locator(mticker.MultipleLocator(.2))
    #plt.show()
    #fig = subplots.make_subplots(rows=3, cols=1)
    for var, vals in func_locals.items():
        fig.add_trace(go.Scatter(
            x=steps, 
            y=vals,
            hoveron='points+fills',
            hovertemplate='size: %{y}',
            #hovertext="test",
            hoverinfo="all",
            mode='lines',
            stackgroup='one',
            name=var,
        ), row=row, col=col)
    #px.area(local_df, x="step", y="value", color="var_name", line_group="var_name", title=fname)
    #fig.update_traces(
    #    hoveron="fills",
    #)


def main():
    parser = argparse.ArgumentParser()

    parser.add_argument("-l", "--locals", help="Locals file generated by local_size.py script.", type=pathlib.Path)
    parser.add_argument("-c", "--combined", help="Combine all charts as subgraphs in the same figure (may cause them to be quite small)", action='store_true')

    args = parser.parse_args()

    local_data = load_locals(args.locals)
    funcs = list(local_data.keys())
    if args.combined:
        fig = subplots.make_subplots(rows=3, cols=1, subplot_titles=funcs)
    else:
        fig = go.Figure()
    for i, key in enumerate(funcs):
        local_df = func_df(local_data[key])
        print(local_df["var_name"].unique())
        if args.combined:
            plot_func(key, local_df, local_data[key], fig, i+1, 1)
        else:
            plot_func(key, local_df, local_data[key], fig)
            fig.update_layout(showlegend=False, title_text=f"{args.locals.stem} - {key}", 
                xaxis=dict(
                    title=dict(
                        text="Source Line"
                    )
                ),
                yaxis=dict(
                    title=dict(
                        text="Memory (Bytes)"
                    )
                ),
            )
            fig.write_html(f"mem-{args.locals.stem}_{key}.html")
            fig.show()
            fig.data = []
    if args.combined:
        fig.update_layout(showlegend=False, title_text=args.locals.stem)
        fig.write_html(f"mem-{args.locals.stem}_combined.html")
        fig.show()

if __name__ == "__main__":
    main()
